### ISSUE TITLE
Remove all MAINTAINER instructions

### ISSUE THREAD

**Issue by ruffsl** [osrf/docker_templates#11]
Just found out MAINTAINER is now deprecated in Docker 1.13: https://github.com/docker/docker/pull/25466

Propose switching to using label instead?

``` diff
-MAINTAINER name <email>
+ LABEL maintainer "name <email>"
```

**Comment by j-rivero** [comment]
+1

**Comment by ruffsl** [comment]
I asked some of the docker library maintainers [1], and I'm now inclined to remove them entirely.
They somewhat pollutes and possible attribute maintainership for downstream images out of our jurisdiction.
The OSRF docker_images repo, and official docker hub doc page should provide sufficient contact info.

I'll update the templates to use `LABEL`, but just redact the use of maintainer from the `images.yaml.em` files.


[1] https://botbot.me/freenode/docker-library/2017-01-26/?msg=80003033&page=1
