### ISSUE TITLE
Repository name

### ISSUE THREAD

**Issue by scpeters** [osrf/docker_templates#2]
Why does this repository have the same name as https://github.com/osrf/docker_images ? @ruffsl @tfoote

**Comment by tfoote** [comment]
I think this was an early version. @ruffsl we don't need this version anymore right?

**Comment by scpeters** [comment]
This is where all the templates are hosted

**Comment by ruffsl** [comment]
Like @scpeters mentioned, this is where my PR with all the template code is pointed to: https://github.com/ros-infrastructure/docker_images/pull/1

Perhaps we could take this time and think where and how we want to separate and store the template code for ROS, Gazebo, DRCSim + and future OSRF docker template code?

**Comment by scpeters** [comment]
cc @j-rivero

We keep a lot of gazebo build scripts in [osrf/release-tools on bitbucket](https://bitbucket.org/osrf/release-tools/src/a861c5cfc338593d8602580626f0f2bf739db7a4/jenkins-scripts/docker/?at=default), but I wouldn't mind keeping our templates next to the ROS ones in order to mutually benefit from improvements.

**Comment by ruffsl** [comment]
Keeping them in one place would make it easier to share a lot of the sippit permatives.

**Comment by tfoote** [comment]
It sounds like we should update the readme on this repo to be clear it holds the templates used to generate the images in the osrf repo and link to it.

**Comment by scpeters** [comment]
Should the templates be moved to the osrf/docker_images repo?

**Comment by ruffsl** [comment]
yea... its outgrown ros-infrastructure a bit. 
Having them under osrf/docker_images or osrf/* would probably clearer.

Additionally, we could also clean out the "docs" and "offical-images" repos in ros-industrial too. The PRs to docker-library for image mannince might best come from OSRF rather than ros-infrastructure?

**Comment by tfoote** [comment]
Yeah, I can move those repos as is. They do make a little bit more sense to be branded osrf with gazebo inside as well, and being hosted on the osrf dockerhub account.

**Comment by tfoote** [comment]
I think keeping the templates separate from the generated output is a good idea. The templates want to be under a very strong version control while the generated output will generate a lot of noise when reviewing changes.

**Comment by scpeters** [comment]
That makes sense; they don't have to be in the same repository. Should we move this to `osrf/docker_templates`?

**Comment by ruffsl** [comment]
@scpeters +1

**Comment by j-rivero** [comment]
I agree with your proposed solution. Seems like the scope if the whole OSRF, so under osrf/ sounds a good solution to me.

**Comment by scpeters** [comment]
bump

**Comment by tfoote** [comment]
Sounds good. I'll rename and transfer it.

**Comment by tfoote** [comment]
Moved. Part two of this is to rename the python modules in the code.
