### ISSUE TITLE
Source install templates for releases (e.g. ardent-source, bouncy-source)

### ISSUE THREAD

**Issue by calvertdw** [osrf/docker_templates#42]
It would be great if we had some Docker images that come with source installations. I can contribute this feature.

**Comment by mikaelarguedas** [comment]
@calvertdw as https://github.com/osrf/docker_images/pull/175 has been resolved and the lack on activity here, I'm going to close this. Feel free to coment here if this is still an issue and it can be reopened

**Comment by calvertdw** [comment]
@mikaelarguedas Is he back!???

**Comment by mikaelarguedas** [comment]
@calvertdw Nope, just doing a flyby on repos I used to maintain when I have some time ;)
