### ISSUE TITLE
Correct MAINTAINER entries for several docker templates

### ISSUE THREAD

**Issue by dirk-thomas** [osrf/docker_templates#6]
Several docker templates list me as the maintainer but I have never touched any of them and am certainly not maintaining them. The same goes for some other files.

Please update the `MAINTAINER` value for all the templates to a person who is actually maintaining these images. Like either @tfoote or @ruffsl ?

**Comment by ruffsl** [comment]
@tfoote , would you want to be listed or have me?
I can make the changes before I make a new PR to the official library after https://github.com/osrf/docker_images/pull/31 .

**Comment by tfoote** [comment]
@ruffsl I'm happy if you want to be listed. Otherwise you can point it to me.

**Comment by ruffsl** [comment]
I'm editing the template code so the `platform.yaml` takes a maintainer argument, and can set it to use this string for now:
``` yaml
    maintainer_name: Tully Foote tfoote+buildfarm@osrfoundation.org
```

**Comment by dirk-thomas** [comment]
There are several other template with "wrong" maintainers. So I reopened this.

**Comment by ruffsl** [comment]
@scpeters , would you want to be listed as maintainer for the official gazebo images?
You work with gazebo more frequently than Tully, and perhaps use the docker images more than Nate, and you have also used the template engine before to create the drc images. Is there say a buildfarm email address you use?

**Comment by scpeters** [comment]
Sure, scpeters+buildfarm at osrfoundation dot org

**Comment by ruffsl** [comment]
Sorry about that @dirk-thomas , if you see anything else, just mention it, or feel free to close.

**Comment by dirk-thomas** [comment]
No, problem, I was just surprised how it got in there in the first place. Thanks for updating it so fast. I will close this.
